### PR TITLE
Upgrading Cypress version to 10.3.0

### PR DESCRIPTION
**Pull request by fjtrujy**

### CODE REVIEW

**Comment by pedrovgs** [comment]
@fjtrujy before releasing anything, be careful and test locally. We fixed the version to cypress 8.5 because it was faster than any other release. If we increase Cypress version now but it is not faster, we may want to stay in cypress 8.5 for a while or update the version and check what we can do to improve performance.

**Comment by pedrovgs** [comment]
Let me know if you need me to run some experiments locally.

**Comment by fjtrujy** [comment]
@pedrovgs https://github.com/GoodNotes/GoodNotes-5/pull/8601 has CI ✅  I think that we can safely merge this

**Comment by fjtrujy** [comment]
Closing PR because cypress is not working properly running it in localhost

**Pull request closed without merging**
